version: "3.8"
services:
    app:
        container_name: node-hellow
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "9012:80"